--Postgresql

CREATE TABLE "DEV"."DUMMY_EMPLOYEES" (
	"EMPLOYEE_ID" numeric(6, 1) NOT NULL,
	"FIRST_NAME" varchar(20) NULL,
	"LAST_NAME" varchar(20) NULL,
	"EMAIL" varchar(20) NULL,
	"PHONE_NUMBER" varchar(20) NULL,
	"HIRE_DATE" date NULL,
	"JOB_ID" varchar(10) NULL,
	"SALARY" numeric(8, 2) NULL,
	"COMMISSION_PCT" numeric(2, 2) NULL,
	"MANAGER_ID" numeric(10, 1) NULL,
	"DEPARTMENT_ID" numeric(10, 1) NULL,
	CONSTRAINT "DUMMY_EMPLOYEES_pkey" PRIMARY KEY ("EMPLOYEE_ID")
);

INSERT INTO "DEV"."DUMMY_EMPLOYEES"
("EMPLOYEE_ID", "FIRST_NAME", "LAST_NAME", "EMAIL", "PHONE_NUMBER", "HIRE_DATE", "JOB_ID", "SALARY", "COMMISSION_PCT", "MANAGER_ID", "DEPARTMENT_ID")
VALUES(100, 'Steven', 'King', 'SKING', '515.123.4567', TIMESTAMP '2003-06-17 00:00:00.000000', 'AD_PRES', 24000, NULL, NULL, 90);
INSERT INTO "DEV"."DUMMY_EMPLOYEES"
("EMPLOYEE_ID", "FIRST_NAME", "LAST_NAME", "EMAIL", "PHONE_NUMBER", "HIRE_DATE", "JOB_ID", "SALARY", "COMMISSION_PCT", "MANAGER_ID", "DEPARTMENT_ID")
VALUES(101, 'Neena', 'Kochhar', 'NKOCHHAR', '515.123.4568', TIMESTAMP '2005-09-21 00:00:00.000000', 'AD_VP', 17000, NULL, 100, 90);
INSERT INTO "DEV"."DUMMY_EMPLOYEES"
("EMPLOYEE_ID", "FIRST_NAME", "LAST_NAME", "EMAIL", "PHONE_NUMBER", "HIRE_DATE", "JOB_ID", "SALARY", "COMMISSION_PCT", "MANAGER_ID", "DEPARTMENT_ID")
VALUES(102, 'Lex', 'De Haan', 'LDEHAAN', '515.123.4569', TIMESTAMP '2001-01-13 00:00:00.000000', 'AD_VP', 17000, NULL, 100, 90);
INSERT INTO "DEV"."DUMMY_EMPLOYEES"
("EMPLOYEE_ID", "FIRST_NAME", "LAST_NAME", "EMAIL", "PHONE_NUMBER", "HIRE_DATE", "JOB_ID", "SALARY", "COMMISSION_PCT", "MANAGER_ID", "DEPARTMENT_ID")
VALUES(103, 'Alexander', 'Hunold', 'AHUNOLD', '590.423.4567', TIMESTAMP '2006-01-03 00:00:00.000000', 'IT_PROG', 9000, NULL, 102, 60);
INSERT INTO "DEV"."DUMMY_EMPLOYEES"
("EMPLOYEE_ID", "FIRST_NAME", "LAST_NAME", "EMAIL", "PHONE_NUMBER", "HIRE_DATE", "JOB_ID", "SALARY", "COMMISSION_PCT", "MANAGER_ID", "DEPARTMENT_ID")
VALUES(104, 'Bruce', 'Ernst', 'BERNST', '590.423.4568', TIMESTAMP '2007-05-21 00:00:00.000000', 'IT_PROG', 6000, NULL, 103, 60);
INSERT INTO "DEV"."DUMMY_EMPLOYEES"
("EMPLOYEE_ID", "FIRST_NAME", "LAST_NAME", "EMAIL", "PHONE_NUMBER", "HIRE_DATE", "JOB_ID", "SALARY", "COMMISSION_PCT", "MANAGER_ID", "DEPARTMENT_ID")
VALUES(105, 'David', 'Austin', 'DAUSTIN', '590.423.4569', TIMESTAMP '2005-06-25 00:00:00.000000', 'IT_PROG', 4800, NULL, 103, 60);
INSERT INTO "DEV"."DUMMY_EMPLOYEES"
("EMPLOYEE_ID", "FIRST_NAME", "LAST_NAME", "EMAIL", "PHONE_NUMBER", "HIRE_DATE", "JOB_ID", "SALARY", "COMMISSION_PCT", "MANAGER_ID", "DEPARTMENT_ID")
VALUES(106, 'Valli', 'Pataballa', 'VPATABAL', '590.423.4560', TIMESTAMP '2006-02-05 00:00:00.000000', 'IT_PROG', 4800, NULL, 103, 60);
INSERT INTO "DEV"."DUMMY_EMPLOYEES"
("EMPLOYEE_ID", "FIRST_NAME", "LAST_NAME", "EMAIL", "PHONE_NUMBER", "HIRE_DATE", "JOB_ID", "SALARY", "COMMISSION_PCT", "MANAGER_ID", "DEPARTMENT_ID")
VALUES(107, 'Diana', 'Lorentz', 'DLORENTZ', '590.423.5567', TIMESTAMP '2007-02-07 00:00:00.000000', 'IT_PROG', 4200, NULL, 103, 60);
INSERT INTO "DEV"."DUMMY_EMPLOYEES"
("EMPLOYEE_ID", "FIRST_NAME", "LAST_NAME", "EMAIL", "PHONE_NUMBER", "HIRE_DATE", "JOB_ID", "SALARY", "COMMISSION_PCT", "MANAGER_ID", "DEPARTMENT_ID")
VALUES(108, 'Nancy', 'Greenberg', 'NGREENBE', '515.124.4569', TIMESTAMP '2002-08-17 00:00:00.000000', 'FI_MGR', 12008, NULL, 101, 100);
INSERT INTO "DEV"."DUMMY_EMPLOYEES"
("EMPLOYEE_ID", "FIRST_NAME", "LAST_NAME", "EMAIL", "PHONE_NUMBER", "HIRE_DATE", "JOB_ID", "SALARY", "COMMISSION_PCT", "MANAGER_ID", "DEPARTMENT_ID")
VALUES(109, 'Daniel', 'Faviet', 'DFAVIET', '515.124.4169', TIMESTAMP '2002-08-16 00:00:00.000000', 'FI_ACCOUNT', 9000, NULL, 108, 100);
INSERT INTO "DEV"."DUMMY_EMPLOYEES"
("EMPLOYEE_ID", "FIRST_NAME", "LAST_NAME", "EMAIL", "PHONE_NUMBER", "HIRE_DATE", "JOB_ID", "SALARY", "COMMISSION_PCT", "MANAGER_ID", "DEPARTMENT_ID")
VALUES(110, 'John', 'Chen', 'JCHEN', '515.124.4269', TIMESTAMP '2005-09-28 00:00:00.000000', 'FI_ACCOUNT', 8200, NULL, 108, 100);
INSERT INTO "DEV"."DUMMY_EMPLOYEES"
("EMPLOYEE_ID", "FIRST_NAME", "LAST_NAME", "EMAIL", "PHONE_NUMBER", "HIRE_DATE", "JOB_ID", "SALARY", "COMMISSION_PCT", "MANAGER_ID", "DEPARTMENT_ID")
VALUES(111, 'Ismael', 'Sciarra', 'ISCIARRA', '515.124.4369', TIMESTAMP '2005-09-30 00:00:00.000000', 'FI_ACCOUNT', 7700, NULL, 108, 100);
INSERT INTO "DEV"."DUMMY_EMPLOYEES"
("EMPLOYEE_ID", "FIRST_NAME", "LAST_NAME", "EMAIL", "PHONE_NUMBER", "HIRE_DATE", "JOB_ID", "SALARY", "COMMISSION_PCT", "MANAGER_ID", "DEPARTMENT_ID")
VALUES(112, 'Jose Manuel', 'Urman', 'JMURMAN', '515.124.4469', TIMESTAMP '2006-03-07 00:00:00.000000', 'FI_ACCOUNT', 7800, NULL, 108, 100);
INSERT INTO "DEV"."DUMMY_EMPLOYEES"
("EMPLOYEE_ID", "FIRST_NAME", "LAST_NAME", "EMAIL", "PHONE_NUMBER", "HIRE_DATE", "JOB_ID", "SALARY", "COMMISSION_PCT", "MANAGER_ID", "DEPARTMENT_ID")
VALUES(113, 'Luis', 'Popp', 'LPOPP', '515.124.4567', TIMESTAMP '2007-12-07 00:00:00.000000', 'FI_ACCOUNT', 6900, NULL, 108, 100);
INSERT INTO "DEV"."DUMMY_EMPLOYEES"
("EMPLOYEE_ID", "FIRST_NAME", "LAST_NAME", "EMAIL", "PHONE_NUMBER", "HIRE_DATE", "JOB_ID", "SALARY", "COMMISSION_PCT", "MANAGER_ID", "DEPARTMENT_ID")
VALUES(114, 'Den', 'Raphaely', 'DRAPHEAL', '515.127.4561', TIMESTAMP '2002-12-07 00:00:00.000000', 'PU_MAN', 11000, NULL, 100, 30);


---MYSQL
CREATE TABLE `DUMMY_DEPARTMENTS` (
  `DEPARTMENT_ID` int(11) NOT NULL,
  `DEPARTMENT_NAME` varchar(30) COLLATE utf8mb4_spanish_ci DEFAULT NULL,
  PRIMARY KEY (`DEPARTMENT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_spanish_ci;

INSERT INTO DUMMY_DEPARTMENTS
(DEPARTMENT_ID, DEPARTMENT_NAME)
VALUES(10, 'Administration');
INSERT INTO DUMMY_DEPARTMENTS
(DEPARTMENT_ID, DEPARTMENT_NAME)
VALUES(20, 'Marketing');
INSERT INTO DUMMY_DEPARTMENTS
(DEPARTMENT_ID, DEPARTMENT_NAME)
VALUES(30, 'Purchasing');
INSERT INTO DUMMY_DEPARTMENTS
(DEPARTMENT_ID, DEPARTMENT_NAME)
VALUES(40, 'Human Resources');
INSERT INTO DUMMY_DEPARTMENTS
(DEPARTMENT_ID, DEPARTMENT_NAME)
VALUES(50, 'Shipping');
INSERT INTO DUMMY_DEPARTMENTS
(DEPARTMENT_ID, DEPARTMENT_NAME)
VALUES(60, 'IT');
INSERT INTO DUMMY_DEPARTMENTS
(DEPARTMENT_ID, DEPARTMENT_NAME)
VALUES(70, 'Public Relations');
INSERT INTO DUMMY_DEPARTMENTS
(DEPARTMENT_ID, DEPARTMENT_NAME)
VALUES(80, 'Sales');
INSERT INTO DUMMY_DEPARTMENTS
(DEPARTMENT_ID, DEPARTMENT_NAME)
VALUES(90, 'Executive');
INSERT INTO DUMMY_DEPARTMENTS
(DEPARTMENT_ID, DEPARTMENT_NAME)
VALUES(100, 'Finance');
INSERT INTO DUMMY_DEPARTMENTS
(DEPARTMENT_ID, DEPARTMENT_NAME)
VALUES(110, 'Accounting');
INSERT INTO DUMMY_DEPARTMENTS
(DEPARTMENT_ID, DEPARTMENT_NAME)
VALUES(120, 'Treasury');
INSERT INTO DUMMY_DEPARTMENTS
(DEPARTMENT_ID, DEPARTMENT_NAME)
VALUES(130, 'Corporate Tax');
INSERT INTO DUMMY_DEPARTMENTS
(DEPARTMENT_ID, DEPARTMENT_NAME)
VALUES(140, 'Control And Credit');
INSERT INTO DUMMY_DEPARTMENTS
(DEPARTMENT_ID, DEPARTMENT_NAME)
VALUES(150, 'Shareholder Services');
INSERT INTO DUMMY_DEPARTMENTS
(DEPARTMENT_ID, DEPARTMENT_NAME)
VALUES(160, 'Benefits');
INSERT INTO DUMMY_DEPARTMENTS
(DEPARTMENT_ID, DEPARTMENT_NAME)
VALUES(170, 'Manufacturing');
INSERT INTO DUMMY_DEPARTMENTS
(DEPARTMENT_ID, DEPARTMENT_NAME)
VALUES(180, 'Construction');
INSERT INTO DUMMY_DEPARTMENTS
(DEPARTMENT_ID, DEPARTMENT_NAME)
VALUES(190, 'Contracting');
INSERT INTO DUMMY_DEPARTMENTS
(DEPARTMENT_ID, DEPARTMENT_NAME)
VALUES(200, 'Operations');
INSERT INTO DUMMY_DEPARTMENTS
(DEPARTMENT_ID, DEPARTMENT_NAME)
VALUES(210, 'IT Support');
INSERT INTO DUMMY_DEPARTMENTS
(DEPARTMENT_ID, DEPARTMENT_NAME)
VALUES(220, 'NOC');
INSERT INTO DUMMY_DEPARTMENTS
(DEPARTMENT_ID, DEPARTMENT_NAME)
VALUES(230, 'IT Helpdesk');
INSERT INTO DUMMY_DEPARTMENTS
(DEPARTMENT_ID, DEPARTMENT_NAME)
VALUES(240, 'Government Sales');
INSERT INTO DUMMY_DEPARTMENTS
(DEPARTMENT_ID, DEPARTMENT_NAME)
VALUES(250, 'Retail Sales');
INSERT INTO DUMMY_DEPARTMENTS
(DEPARTMENT_ID, DEPARTMENT_NAME)
VALUES(260, 'Recruiting');
INSERT INTO DUMMY_DEPARTMENTS
(DEPARTMENT_ID, DEPARTMENT_NAME)
VALUES(270, 'Payroll');
